(import (rnrs))

(define (roman n)
  (let loop ((n n) (acc '()))
    (cond ((>= n 1000) (loop (- n 1000) (cons  "M" acc)))
          ((>= n  900) (loop (- n  900) (cons "CM" acc)))
          ((>= n  500) (loop (- n  500) (cons  "D" acc)))
          ((>= n  400) (loop (- n  400) (cons "CD" acc)))
          ((>= n  100) (loop (- n  100) (cons  "C" acc)))
          ((>= n   90) (loop (- n   90) (cons "XC" acc)))
          ((>= n   50) (loop (- n   50) (cons  "L" acc)))
          ((>= n   40) (loop (- n   40) (cons "XL" acc)))
          ((>= n   10) (loop (- n   10) (cons  "X" acc)))
          ((>= n    9) (loop (- n    9) (cons "IX" acc)))
          ((>= n    5) (loop (- n    5) (cons  "V" acc)))
          ((>= n    4) (loop (- n    4) (cons "IV" acc)))
          ((>= n    1) (loop (- n    1) (cons  "I" acc)))
          (else (string-join (reverse acc) "")))))
