# By default, list available recipes
_default:
    @just --list

_dontknow:
    @echo "Don't know how to do that yet"

# Clean up
clean:
    @just _dontknow

# Run linters, static analysers and so on
check target:
    @echo 'Checking {{invocation_directory()}}/{{target}} ..'
    @just _dontknow

# Auto-format code file
style target:
    @echo 'Styling {{invocation_directory()}}/{{target}}...'
    @just _dontknow

# Run tests
test target:
    #!/usr/bin/env bash
    set -euo pipefail
    echo 'Testing {{file_name(invocation_directory())}}...'
    cd {{invocation_directory()}}
    swipl -f {{target}}.pl -s {{target}}_tests.plt -g run_tests,halt -t 'halt(1)' -- --all mix test --include pending

# Run style, lint, tests, submit to exercism, git commit
submit target *more_files:
    #!/usr/bin/env bash
    set -euo pipefail
    echo 'Submitting {{invocation_directory()}}/...'
    cd {{invocation_directory()}}
    just style {{target}}.pl
    just check {{target}}.pl
    just test {{target}}
    exercism submit {{target}}.pl {{more_files}}
    git add .
    git commit -m 'exercism:prolog:{{file_name(invocation_directory())}}'
