# By default, list available recipes
_default:
    @just --list

_dontknow:
    @echo "Don't know how to do that yet"

# Clean up
clean:
    @just _dontknow

# Run linters, static analysers and so on
check target:
    @echo 'Checking {{invocation_directory()}}/{{target}} ..'
    @just _dontknow

# Auto-format code file
style target:
    @echo 'Styling {{invocation_directory()}}/{{target}}...'
    @just _dontknow

# Run tests
test target:
    #!/usr/bin/env bash
    set -euo pipefail
    echo 'Testing {{file_name(invocation_directory())}}...'
    cd {{invocation_directory()}}
    emacs -q -batch -l ert -l {{target}}-test.el -f ert-run-tests-batch-and-exit

# Run style, lint, tests, submit to exercism, git commit
submit target *more_files:
    #!/usr/bin/env bash
    set -euo pipefail
    echo 'Submitting {{invocation_directory()}}/...'
    cd {{invocation_directory()}}
    just style {{target}}.el
    just check {{target}}.el
    just test {{target}}
    exercism submit {{target}}.el {{more_files}}
    git add .
    git commit -m 'exercism:emacs-lisp:{{file_name(invocation_directory())}}'
