name: rotational-cipher
version: 1.2.0.4

dependencies:
  - base

library:
  exposed-modules: RotationalCipher
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - containers

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - rotational-cipher
      - hspec
