select = [
    "E", "F", "I", "W", "RET", "SIM", "UP", "S", "B", "A", "COM",
    "C90", "C4", "G", "ERA", "PLC",
    # pylint (PL)
    "PLE", "PLR", "PLW",
    # ruff specific rules
    "RUF",
]
ignore = [
    # trailing comma missing
    "COM812",
    # use of assert detected
    "S101",
    # Unnecessary `else` after `return` statement
    "RET505",
    # Argument is shadowing a python buildin. This is actually pretty bad,
    # but since we already have this historically happening, we would break
    # compatibility with clients.
    "A002",
    # Class attribute is shadowing a python builtin
    "A003",
    # Too many arguments in function call. Again, we don't want to break clients.
    "PLR0913",
    # Magic value used in comparison, consider replacing 200 with a constant variable.
    # We use lots of HTTP status codes, would not make sense to replace them.
    "PLR2004",
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = [
    "A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W",
    "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT",
    "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI",
    "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"
]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pycache__",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

# Same as Black.
line-length = 88

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

target-version = "py311"

[per-file-ignores]
# many pylint suggestions are improper for tests
"encapsia_api/tests/*" = ["PLR", "PLW", "PLC1901"]

[mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[isort]
lines-after-imports = 2
