[package]
edition = "2021"
name = "collatz_conjecture"
version = "1.2.1"

[dev-dependencies]
# commented out because it brings in lots of dependencies
# and compilation time takes longer, causing tests to timeout

# criterion = "0.6.0"

[[bench]]
name = "collatz_bench"
harness = false
